---
abstract: 'parse .mwb files created with MySQL Workbench'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132510'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MySQL-Workbench-Parser
requires:
  Archive::Zip: 1.30
  Carp: 0
  File::Basename: 2.82
  File::Spec: 3.40
  List::MoreUtils: 0.33
  Moo: 1.003001
  Scalar::Util: 1.32
  XML::LibXML: 2.0019
  YAML::Tiny: 1.56
resources:
  bugtracker: http://github.com/reneeb/MySQL-Workbench-Parser/issues
  homepage: http://github.com/reneeb/MySQL-Workbench-Parser
  repository: git://github.com/reneeb/MySQL-Workbench-Parser.git
version: 0.01
